const STORAGE_KEY = 'omnitutor_v29';
const state = { apiKey: '', procode: '', chat: [], packets: [], focusPacketId: 'all', quiz: [], attempts: [] };
const el = {};

document.addEventListener('DOMContentLoaded', () => { bindElements(); loadState(); bindEvents(); renderAll(); });
function bindElements() { ['apiKeyInput','saveKeyBtn','procodeEditor','saveProcodeBtn','chatLog','focusSelect','chatForm','promptInput','summarizeBtn','clearChatBtn','packetList','newPacketBtn','generateQuizBtn','quizContainer','mindMap'].forEach(id => { el[id] = document.getElementById(id); }); }
function on(node, event, handler) { node?.addEventListener(event, handler); }
function bindEvents() {
  on(el.saveKeyBtn, 'click', () => { state.apiKey = el.apiKeyInput.value.trim(); persist(); toast('API key saved locally.'); });
  on(el.saveProcodeBtn, 'click', () => { state.procode = el.procodeEditor.value; persist(); toast('ProCode draft saved.'); });
  on(el.chatForm, 'submit', async event => { event.preventDefault(); const prompt = el.promptInput.value.trim(); if (!prompt) return; pushChat('user', prompt); el.promptInput.value = ''; pushChat('ai', await generateTutorResponse(prompt)); persist(); });
  on(el.summarizeBtn, 'click', async () => { const packets = getFocusedPackets(); if (!packets.length) return toast('No packets in focus.'); pushChat('user', '[Summarize Focus]'); pushChat('ai', await generateTutorResponse(`Summarize these notes in concise bullets:\n\n${packets.map(p => p.content).join('\n\n')}`, true)); persist(); });
  on(el.clearChatBtn, 'click', () => { state.chat = []; renderChat(); persist(); });
  on(el.focusSelect, 'change', () => { state.focusPacketId = el.focusSelect.value; renderFocusSelect(); renderPackets(); renderMindMap(); persist(); });
  on(el.newPacketBtn, 'click', () => { const title = prompt('Packet title?'); if (!title) return; const content = prompt('Packet content?'); if (!content) return; state.packets.unshift(createPacket(title, content)); renderPackets(); renderFocusSelect(); renderMindMap(); persist(); });
  on(el.generateQuizBtn, 'click', async () => { state.quiz = await generateQuiz(); renderQuiz(); persist(); });
}
function createPacket(title, content) { return { id: crypto.randomUUID(), title, content, pinned: false, createdAt: Date.now() }; }
function pushChat(role, text) { state.chat.push({ role, text, ts: Date.now() }); renderChat(); }
function getFocusedPackets() { return state.focusPacketId === 'all' ? state.packets : state.packets.filter(p => p.id === state.focusPacketId); }
async function generateTutorResponse(promptText, forceCanvasOnly = false) {
  const focused = getFocusedPackets(); const contextBlock = focused.length ? focused.map((p, i) => `Packet ${i + 1}: ${p.title}\n${p.content}`).join('\n\n') : 'No packet context available.';
  const instruction = forceCanvasOnly || state.focusPacketId !== 'all' ? 'Reason only from the provided packet context. If unknown, say it is outside focus.' : 'Use provided packet context first, then general reasoning as needed.';
  if (!state.apiKey) return `Local OmniTutor response:\n- I used your selected learning context.\n- Next step: ${promptText.slice(0, 90)}\n- Add a Gemini key in Settings for live responses.`;
  try { const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${state.apiKey}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ contents: [{ role: 'user', parts: [{ text: `${instruction}\n\nContext:\n${contextBlock}\n\nUser:\n${promptText}` }] }] }) }); if (!response.ok) throw new Error(`Gemini error: ${response.status}`); const data = await response.json(); return data.candidates?.[0]?.content?.parts?.[0]?.text || 'No response.'; } catch (error) { return `Live model failed (${error.message}). Falling back to local tutor mode.`; }
}
async function generateQuiz() {
  const packets = state.packets.slice(0, 6); if (!packets.length) return [{ q: 'No packets available. Add one to generate a quiz.', options: ['OK'], answer: 0 }];
  if (state.apiKey) { try { const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${state.apiKey}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ contents: [{ parts: [{ text: `Create exactly 3 multiple-choice questions from these notes. Return pure JSON array with keys q, options (4), answerIndex. Notes: ${packets.map(p => p.content).join(' ')}` }] }] }) }); const data = await response.json(); const raw = data.candidates?.[0]?.content?.parts?.[0]?.text || '[]'; return JSON.parse(raw.replace(/```json|```/g, '').trim()).map(item => ({ q: item.q, options: item.options, answer: item.answerIndex })); } catch { /* use local fallback */ } }
  return packets.slice(0, 3).map((p, idx) => ({ q: `Packet ${idx + 1}: Which best captures this idea?`, options: [p.content.split('.').find(Boolean)?.trim() || p.content, 'Unrelated interpretation', 'Opposite claim', 'Insufficient context'], answer: 0 }));
}
function renderAll() { if (el.apiKeyInput) el.apiKeyInput.value = state.apiKey; if (el.procodeEditor) el.procodeEditor.value = state.procode; renderFocusSelect(); renderChat(); renderPackets(); renderQuiz(); renderMindMap(); renderProgress(); }
function renderChat() { if (!el.chatLog) return; el.chatLog.innerHTML = ''; state.chat.forEach(message => { const node = document.createElement('article'); node.className = `msg ${message.role}`; node.innerHTML = `<div class="msg-role">${message.role}</div><div>${escapeHtml(message.text).replace(/\n/g, '<br>')}</div>`; el.chatLog.appendChild(node); }); el.chatLog.scrollTop = el.chatLog.scrollHeight; }
function renderFocusSelect() { if (!el.focusSelect) return; el.focusSelect.innerHTML = ['<option value="all">All packets (default)</option>', ...state.packets.map(p => `<option value="${p.id}">${escapeHtml(p.title)}</option>`)].join(''); el.focusSelect.value = state.focusPacketId; if (el.focusSelect.value !== state.focusPacketId) state.focusPacketId = 'all'; }
function renderPackets() { if (!el.packetList) return; el.packetList.innerHTML = ''; if (!state.packets.length) { el.packetList.innerHTML = '<div class="empty-state"><span>▤</span><strong>No knowledge packets yet</strong><small>Save notes in Canvas to give Omni useful context.</small></div>'; renderProgress(); return; } state.packets.forEach(packet => { const card = document.createElement('article'); card.className = `packet-card ${state.focusPacketId === packet.id ? 'focused' : ''}`; card.innerHTML = `<div class="packet-title"><strong>${escapeHtml(packet.title)}</strong><div class="packet-actions"><button class="btn" data-action="focus">Focus</button><button class="btn" data-action="pin">${packet.pinned ? 'Unpin' : 'Pin'}</button><button class="btn" data-action="delete">Delete</button></div></div><p>${escapeHtml(packet.content).slice(0, 240)}</p>`; on(card.querySelector('[data-action="focus"]'), 'click', () => { state.focusPacketId = packet.id; renderFocusSelect(); renderPackets(); renderMindMap(); persist(); }); on(card.querySelector('[data-action="pin"]'), 'click', () => { packet.pinned = !packet.pinned; renderPackets(); renderMindMap(); persist(); }); on(card.querySelector('[data-action="delete"]'), 'click', () => { state.packets = state.packets.filter(p => p.id !== packet.id); if (state.focusPacketId === packet.id) state.focusPacketId = 'all'; renderFocusSelect(); renderPackets(); renderMindMap(); persist(); }); el.packetList.appendChild(card); }); renderProgress(); }
function renderQuiz() { if (!el.quizContainer) return; el.quizContainer.innerHTML = ''; if (!state.quiz.length) { el.quizContainer.innerHTML = '<div class="empty-state"><span>◒</span><strong>No practice set yet</strong><small>Add a packet, then generate a short quiz.</small></div>'; return; } state.quiz.forEach((item, index) => { const card = document.createElement('article'); card.className = 'quiz-card'; card.innerHTML = `<h3>Question ${index + 1}</h3><p>${escapeHtml(item.q)}</p><div class="quiz-options">${item.options.map((option, i) => `<button class="btn quiz-choice" data-choice="${i}">${String.fromCharCode(65 + i)}. ${escapeHtml(option)}</button>`).join('')}</div><p class="quiz-feedback" data-feedback></p>`; card.querySelectorAll('[data-choice]').forEach(button => on(button, 'click', () => { if (card.dataset.answered) return; card.dataset.answered = 'true'; const correct = Number(button.dataset.choice) === item.answer; card.querySelector('[data-feedback]').textContent = correct ? 'Correct.' : `Review answer ${String.fromCharCode(65 + item.answer)}.`; card.querySelectorAll('.quiz-choice').forEach(choice => choice.disabled = true); if (document.querySelectorAll('.quiz-card[data-answered="true"]').length === state.quiz.length) { const score = [...document.querySelectorAll('.quiz-card')].filter(c => c.querySelector('[data-feedback]').textContent === 'Correct.').length; state.attempts.unshift({ score, total: state.quiz.length, ts: Date.now() }); state.attempts = state.attempts.slice(0, 20); persist(); renderProgress(); const status = document.getElementById('practiceState'); if (status) status.textContent = `Complete · ${score}/${state.quiz.length}`; } })); el.quizContainer.appendChild(card); }); }
function renderMindMap() { if (!el.mindMap) return; el.mindMap.innerHTML = ''; const center = { x: 160, y: 105 }; const nodes = state.packets.filter(p => p.pinned || state.focusPacketId === p.id).slice(0, 10); const core = document.createElementNS('http://www.w3.org/2000/svg', 'circle'); core.setAttribute('cx', center.x); core.setAttribute('cy', center.y); core.setAttribute('r', 13); core.setAttribute('fill', '#5eead4'); el.mindMap.appendChild(core); nodes.forEach((node, index) => { const angle = Math.PI * 2 * index / Math.max(nodes.length, 1); const x = center.x + Math.cos(angle) * 72; const y = center.y + Math.sin(angle) * 72; const line = document.createElementNS('http://www.w3.org/2000/svg', 'line'); line.setAttribute('x1', center.x); line.setAttribute('y1', center.y); line.setAttribute('x2', x); line.setAttribute('y2', y); line.setAttribute('stroke', '#33475e'); el.mindMap.appendChild(line); const dot = document.createElementNS('http://www.w3.org/2000/svg', 'circle'); dot.setAttribute('cx', x); dot.setAttribute('cy', y); dot.setAttribute('r', 7); dot.setAttribute('fill', node.pinned ? '#5eead4' : '#a78bfa'); el.mindMap.appendChild(dot); }); }
function renderProgress() { const packetCount = document.getElementById('progressPackets'); const attemptCount = document.getElementById('progressAttemptsCount'); const score = document.getElementById('progressScore'); const label = document.getElementById('progressAttempts'); if (packetCount) packetCount.textContent = state.packets.length; if (attemptCount) attemptCount.textContent = state.attempts.length; if (state.attempts.length && score) { const average = state.attempts.reduce((sum, attempt) => sum + attempt.score / Math.max(attempt.total, 1) * 100, 0) / state.attempts.length; score.textContent = `${Math.round(average)}%`; if (label) label.textContent = `${state.attempts[0].score}/${state.attempts[0].total} on latest quiz`; } }
function loadState() { try { const parsed = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}'); Object.assign(state, parsed); state.attempts ||= []; } catch { /* keep defaults */ } }
function persist() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function toast(message) { console.info(`[OmniTutor] ${message}`); }
function escapeHtml(value = '') { return String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;'); }
