from pathlib import Path

ROOT = Path(__file__).parent / 'app'
ROOT.mkdir(exist_ok=True)

NAV = [
    ('assistant.html', '✦', 'Assistant'), ('canvas.html', '▤', 'Knowledge Canvas'),
    ('practice.html', '◒', 'Practice'), ('code.html', '⌘', 'Code Lab'),
    ('map.html', '⌁', 'Mind Map'), ('progress.html', '↗', 'Progress'),
    ('settings.html', '⚙', 'Settings')
]

PAGES = {
'assistant.html': ('Assistant', '''<section class="page-intro"><div><span class="kicker">NEURAL HUB</span><h1>What are you learning today?</h1><p>Ask a question, work through a problem, or get a clear study plan.</p></div><span class="status-pill">● Local tutor mode</span></section><div class="assistant-grid"><section class="surface chat-surface"><div class="surface-head"><div><h2>Omni Tutor</h2><p>Context-aware learning support</p></div><select id="focusSelect" class="context-select"><option value="all">All knowledge</option></select></div><div id="chatLog" class="chat-log"><div class="empty-chat"><div class="tutor-avatar">✦</div><h2>Start with a question</h2><p>I can explain concepts, guide problem solving, or turn notes into a study plan.</p><div class="suggestion-list"><button class="suggestion" data-prompt="Explain a difficult concept simply"><b>Explain something</b><small>Break down a hard idea</small></button><button class="suggestion" data-prompt="Help me solve a problem step by step"><b>Work through a problem</b><small>Learn the reasoning</small></button><button class="suggestion" data-prompt="Create a study plan for this topic"><b>Plan a study session</b><small>Know what to do next</small></button></div></div></div><form id="chatForm" class="chat-composer"><input id="promptInput" class="input" placeholder="Ask Omni anything…" autocomplete="off"><button class="primary-button" type="submit">Send ↗</button></form><div class="chat-meta"><span>Answers use your selected Canvas context</span><button id="summarizeBtn">Summarize context</button><button id="clearChatBtn">Clear</button></div></section><aside class="surface context-surface"><div class="surface-head"><div><h2>Learning context</h2><p>Your active knowledge</p></div><a class="plus-button" href="canvas.html">+</a></div><div id="packetList" class="packet-list"><div class="empty-state"><span>▤</span><strong>No knowledge packets yet</strong><small>Save notes in Canvas to give Omni useful context.</small></div></div><div class="context-footer"><b>Tip</b><p>Focus a packet to keep answers grounded in one topic.</p></div></aside></div>'''),
'canvas.html': ('Knowledge Canvas', '''<section class="page-intro"><div><span class="kicker">KNOWLEDGE CANVAS</span><h1>Your ideas, organized.</h1><p>Capture explanations and notes so they become reusable learning context.</p></div><button id="newPacketBtn" class="primary-button">+ New packet</button></section><section class="surface canvas-surface"><div class="surface-head"><div><h2>All knowledge packets</h2><p>Saved in this browser</p></div><input class="search-input" placeholder="Search packets…"></div><div id="packetList" class="packet-list canvas-list"><div class="empty-state"><span>▤</span><strong>Your Canvas is empty</strong><small>Capture your first useful idea from a tutoring session.</small></div></div></section>'''),
'practice.html': ('Practice', '''<section class="page-intro"><div><span class="kicker">QUIZ ENGINE</span><h1>Practice what you know.</h1><p>Active recall turns a good explanation into knowledge you can use.</p></div><button id="generateQuizBtn" class="primary-button">Generate quiz</button></section><section class="surface practice-surface"><div class="surface-head"><div><h2>Current practice set</h2><p>Generated from your saved packets</p></div><span id="practiceState" class="status-pill">Not started</span></div><div id="quizContainer" class="quiz-container"><div class="empty-state"><span>◒</span><strong>No practice set yet</strong><small>Add a packet, then generate a short quiz.</small></div></div></section>'''),
'progress.html': ('Progress', '''<section class="page-intro"><div><span class="kicker">PROGRESS</span><h1>See your learning signals.</h1><p>Progress comes from real practice and review activity.</p></div></section><div class="progress-cards"><div class="metric-card"><small>KNOWLEDGE PACKETS</small><strong id="progressPackets">0</strong><span>Captured ideas</span></div><div class="metric-card"><small>AVERAGE QUIZ SCORE</small><strong id="progressScore">—</strong><span id="progressAttempts">Complete a quiz to begin</span></div><div class="metric-card"><small>QUIZ ATTEMPTS</small><strong id="progressAttemptsCount">0</strong><span>Saved in this browser</span></div></div><section class="surface next-surface"><span class="kicker">NEXT STEP</span><h2>Build your next learning signal</h2><p>Add a packet, ask Omni about it, then complete the generated quiz.</p><a class="secondary-button" href="canvas.html">Open Canvas →</a></section>'''),
'settings.html': ('Settings', '''<section class="page-intro"><div><span class="kicker">SETTINGS</span><h1>Make Omni yours.</h1><p>Configure your local model connection and workspace preferences.</p></div></section><section class="surface settings-surface"><div class="settings-row"><div><h2>Gemini connection</h2><p>Your key stays in this browser for this prototype. Production V3 will use a server-side gateway.</p></div><div class="settings-form"><input id="apiKeyInput" class="input" type="password" placeholder="Paste Gemini API key"><button id="saveKeyBtn" class="primary-button">Save key</button></div></div><div class="settings-row"><div><h2>ProCode scratchpad</h2><p>Keep a small code draft alongside your learning sessions.</p></div><div class="settings-form"><textarea id="procodeEditor" class="input" rows="4" placeholder="Draft code here…"></textarea><button id="saveProcodeBtn" class="secondary-button">Save draft</button></div></div></section>'''),
'code.html': ('Code Lab', '''<section class="page-intro"><div><span class="kicker">CODE LAB</span><h1>Learn by building.</h1><p>A focused coding workspace is coming next in the V3 learning engine.</p></div><span class="status-pill">In development</span></section><section class="surface coming-panel"><div class="coming-icon">⌘</div><h2>ProCode Lab</h2><p>JavaScript-first practice with guided explanations, safe execution, console output, and project files will extend V2’s editor into a learning workflow.</p></section>'''),
'map.html': ('Mind Map', '''<section class="page-intro"><div><span class="kicker">MIND MAP</span><h1>See how ideas connect.</h1><p>Pin knowledge packets to build a visual map of your learning.</p></div></section><section class="surface map-surface"><div class="surface-head"><div><h2>Neural map</h2><p>Pinned relationships</p></div></div><svg id="mindMap" viewBox="0 0 320 230" aria-label="Knowledge relationship map"></svg></section>''')
}

def nav(active):
    items = []
    for href, icon, label in NAV:
        cls = 'nav-item active' if href == active else 'nav-item'
        items.append(f'<a class="{cls}" href="{href}"><span>{icon}</span>{label}</a>')
    return ''.join(items)

def page(filename, title, body):
    template = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} | Omni AI Tutor v3</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="../style.css"><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" async></script></head><body class="workspace-page"><div class="app-shell"><aside class="app-sidebar" id="workspaceNav"><a class="app-brand" href="../"><span class="brand-mark">O</span><span>OMNI <em>v3</em></span></a><div class="workspace-select"><span class="workspace-icon">◈</span><span><small>WORKSPACE</small><strong>My learning studio</strong></span></div><div class="nav-label">LEARN</div><nav class="app-nav" aria-label="Workspace navigation">{nav}</nav><div class="sidebar-bottom"><div class="model-status"><i></i><span><strong>Local tutor mode</strong><small>Connect Gemini in Settings</small></span></div><a class="help-link" href="../OMNI_AI_TUTOR_V3_BLUEPRINT.md">Read the V3 blueprint →</a></div></aside><main class="app-main"><header class="app-header"><button id="mobileNavToggle" class="mobile-nav-toggle" aria-label="Open navigation" aria-expanded="false">☰</button><a class="mobile-brand" href="../"><span class="brand-mark">O</span><strong>OMNI <em>v3</em></strong></a><div class="breadcrumbs"><span>My learning studio</span><b>/</b><strong>{title}</strong></div><div class="header-actions"><a href="../blog/" class="header-link">Blog</a><a href="../changelog/" class="header-link">Changelog</a><a href="https://github.com/shonibareakanni009-ctrl/omni-tutor-ai-v3" class="header-icon" aria-label="GitHub">↗</a><button class="avatar">AS</button></div></header><div class="page-content"><div class="foundation-note"><span>V3 FOUNDATION</span><strong>Originally established as OmniTutor v2.9</strong><a href="../changelog/">See what changed ↗</a></div>{body}</div></main></div><script src="../app.js"></script><script>document.querySelectorAll('.suggestion').forEach(b=>b.addEventListener('click',()=>{{const input=document.getElementById('promptInput');if(input){{input.value=b.dataset.prompt;input.focus()}}}}));document.getElementById('mobileNavToggle')?.addEventListener('click',()=>{{const nav=document.getElementById('workspaceNav');const open=nav.classList.toggle('mobile-open');document.getElementById('mobileNavToggle').setAttribute('aria-expanded',String(open))}});document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>document.getElementById('workspaceNav')?.classList.remove('mobile-open')));</script></body></html>'''
    return template.replace('{title}', title).replace('{nav}', nav(filename)).replace('{body}', body)

for filename, (title, body) in PAGES.items():
    (ROOT / filename).write_text(page(filename, title, body), encoding='utf-8')
# Keep index as the assistant entry page for direct /app/ visits.
(ROOT / 'index.html').write_text(page('assistant.html', *PAGES['assistant.html']), encoding='utf-8')
print(f'Generated {len(PAGES)} focused workspace pages in {ROOT}')
